// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4OvIzbNVm1fkyG0zpBczYQHF_WvTbGmQ',
    appId: '1:360794027054:web:691b1fd07900522ef41bbf',
    messagingSenderId: '360794027054',
    projectId: 'final-project-67020',
    authDomain: 'final-project-67020.firebaseapp.com',
    storageBucket: 'final-project-67020.firebasestorage.app',
    measurementId: 'G-K99B6E47P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYsLVr4pfd2ezcn7u0hjWuyx-sSdiOwAE',
    appId: '1:360794027054:android:446bd6e6bda0e127f41bbf',
    messagingSenderId: '360794027054',
    projectId: 'final-project-67020',
    storageBucket: 'final-project-67020.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0-L_JTl5LPzrFkwpHIVLd5JGxTb9x2gA',
    appId: '1:360794027054:ios:7f0c983e43b4ee15f41bbf',
    messagingSenderId: '360794027054',
    projectId: 'final-project-67020',
    storageBucket: 'final-project-67020.firebasestorage.app',
    iosBundleId: 'com.example.jobseeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0-L_JTl5LPzrFkwpHIVLd5JGxTb9x2gA',
    appId: '1:360794027054:ios:7f0c983e43b4ee15f41bbf',
    messagingSenderId: '360794027054',
    projectId: 'final-project-67020',
    storageBucket: 'final-project-67020.firebasestorage.app',
    iosBundleId: 'com.example.jobseeker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4OvIzbNVm1fkyG0zpBczYQHF_WvTbGmQ',
    appId: '1:360794027054:web:b959a82f7b1dd0f2f41bbf',
    messagingSenderId: '360794027054',
    projectId: 'final-project-67020',
    authDomain: 'final-project-67020.firebaseapp.com',
    storageBucket: 'final-project-67020.firebasestorage.app',
    measurementId: 'G-9YW8F0ZW0C',
  );
}
